### ISSUE TITLE
add set log level function

### ISSUE THREAD

**Issue by elegantm** [kubernetes/klog#347] opened 2022-08-18 10:37 UTC
/kind feature
**log level output**

set log level must be useful  when debug a online program

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
  ### zap: 
  https://pkg.go.dev/go.uber.org/zap#example-AtomicLevel-Config
`	cfg.Level.SetLevel(zap.ErrorLevel)`
                   
###  logrus   
 https://github.com/sirupsen/logrus
`    log.SetLevel(log.WarnLevel)
`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
without set level ,i use flag package to set log level.  like below
`			

                   //logger *logr.Logger
	                _ = flag.Set("v", "0")

			fmt.Println("set debug log level 0 ", logger.GetSink().Enabled(3))

			flag.Parsed()

			logger.V(2).Info("debug v2")`

**Comment by pohly** [comment] 2022-08-18 13:34
Is this perhaps a duplictate of https://github.com/kubernetes/klog/issues/336?

**Comment by elegantm** [comment] 2022-08-19 08:28
> Is this perhaps a duplicate of #336?

 yeah, the same feature issue

**Comment by pohly** [comment] 2022-08-19 08:56
/close

Duplicate of #336.

**Closed** 2022-08-19 08:56 UTC
Labels: kind/feature
